### ISSUE TITLE
Add Eau Grand Paris Sud

### ISSUE THREAD

**Issue by schumijo** [acesyde/hassio_agur_integration#7]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/acesyde/hassio_agur_integration/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Salut @acesyde 

En parcourant ton code, je remarque que le site Eau Grand Paris Sud fonctionne de la même façon

### Describe the solution you'd like

Penses-tu qu'il est possible d'intégrer proprement la gestion des sites basés sur le même fonctionnement.
Pour Eau Grand Paris, il suffit d'adapter ces 3 variables :

```
BASE_URL: str = "abonne-eau.grandparissud.fr"
CLIENT_ID: str = "AEL-TOKEN-GPS-PRD"
ACCESS_KEY: str = "REGPS-hc-GPS-MP-PRD"
```

Peut-être ajouter une liste déroulante dans la workflow de configuration ?

### Describe alternatives you've considered

Testé et fonctionnel sur mon HA

### Additional context

N/A

**Comment by acesyde** [comment]
👋 @schumijo 

Merci pour l'idée, effectivement en scrutant c'est un prestataire de service qui gère l'infrastructure informatique derrière ainsi que la partie développement logiciel. 

De ce fait il est fort probable que cette intégration fonctionne à pas mal d'endroits.

Au lieu de l'intégrer en mode brut de décoffrage je vais contacter la société pour voir si ils peuvent me fournir la liste de tous led clients eau qu'ils soutraitent ainsi que potentiellement éviter qu'ils nous coupent les vivres 😅

Je te tiens au courant

**Comment by schumijo** [comment]
Salut @acesyde 

Des nouvelles ?

**Comment by acesyde** [comment]
> Salut @acesyde 
> 
> Des nouvelles ?

Salut, Je dois relancer en attendant je vais rajouter tes informations 😉

**Comment by schumijo** [comment]
Salut

J'arrive a passer le wizard d'intégration avec succès mais aucune valeur ne remonte. 

Dans les logs je vois "Invalide Credentials" alors que mon compte est correct
Et je vois aussi :

Logger: homeassistant
Source: data_entry_flow.py:440
First occurred: 07:29:40 (6 occurrences)
Last logged: 07:57:02

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 754, in _async_init_reauth
    await hass.config_entries.flow.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 908, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 385, in _async_handle_step
    self._raise_if_step_does_not_exist(flow, step_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 440, in _raise_if_step_does_not_exist
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ConfigEntriesFlowManager doesn't support step reauth

**Comment by acesyde** [comment]
Salit @schumijo,

La version `0.0.4-beta.2` devrait corriger le probleme désolé ^^
